---
- name: Setup Sentry
  hosts: all
  become: true
  gather_facts: true
  vars_prompt: []
    # - name: deploy_env
    #   prompt: "Which Environment should we target?(dev,prod)"
    #   private: no
    #   default: "dev"
    # - name: user_loging
    #   prompt: "Which user should i use?"
    #   private: no
    #   default: "nikola"
  vars_files:
    - default.yml
  # roles:
  #   - ""
  handlers: []
  roles:
    - role: geerlingguy.pip
      vars:
        pip_install_packages:
          - name: docker
    - role: geerlingguy.docker
      vars:
        docker_compose_version: "v2.12.2"

  pre_tasks:
    - name: Execute prerequsites
      ansible.builtin.include_tasks: tasks/prerequisites.yml
    # - source parse-cli.sh
    # - TODO: source detect-platform.sh
    # - eh? source dc-detect-version.sh
    # - eh? source error-handling.sh
    # - wat? trap_with_arg cleanup ERR INT TERM EXIT
    # - source check-latest-commit.sh
    - name: Execute check-latest-commit
      ansible.builtin.include_tasks: tasks/check-latest-commit.yml

    # - source check-minimum-requirements.sh

  tasks: []
    # - include_tasks:
  post_tasks: []
