- name: Get Git status
  ansible.builtin.command:
    cmd: git status -s
  register: git_status
  when: building.SKIP_COMMIT_CHECK == false
- name: Fail if Git not up to date
  ansible.builtin.fail:
    msg: "Seems like you are not using the latest commit from the self-hosted repository. Please pull the latest changes and try again, or suppress this check with  the building.SKIP_COMMIT_CHECK variable set to true"
  failed_when: git_status | length > 0
  when: building.SKIP_COMMIT_CHECK == false
  
- name: Print git repo status
  ansible.builtin.debug:
    var: git_status
  when: git_status.length > 0

## Tbh, this should be the default..
# - name: Update repo unless skip is specified
#   ansible.builtin.git:
#     repo: ./
#     dest: ./
#     single_branch: yes
#     version: master
#     depth: 2
#     update: yes
#   register: git_repo
#   when: building.SKIP_COMMIT_CHECK == false