---
- name: Get Docker Info
  community.docker.docker_host_info:
  register: docker_info

# - name: Print Docker debug docker_info
#   ansible.builtin.debug:
#     var: docker_info.host_info

- name: Outdated Docker version
  ansible.builtin.assert:
    msg: "{{ docker_info.host_info.ServerVersion }} is older than the minimum docker version of '{{ prerequistes.MIN_DOCKER_VERSION }}' please update."
    that: docker_info.host_info.ServerVersion is version(prerequistes.MIN_DOCKER_VERSION, '>')
    quiet: true

- name: Check CPUs in Docker
  ansible.builtin.assert:
    msg: "{{ docker_info.host_info.NCPU }} vCpus are not enough, you need minimum '{{ prerequistes.MIN_CPU_HARD }}' please add more vCpus to docker"
    that: "{{ (docker_info.host_info.NCPU | int) > prerequistes.MIN_CPU_HARD }}"
    quiet: true

- name: Check Is KVM CPU
  ansible.builtin.command:
    cmd: "docker run --rm busybox grep -c 'Common KVM processor' /proc/cpuinfo"
  register: is_kvm_cpu_check
  ignore_errors: true
  changed_when: false

- name: Set Docker check variables
  ansible.builtin.set_fact:
    docker_ram: "{{ ((docker_info.host_info.MemTotal / 1024 | pow(2)) | round | int) }}"
    is_kvm_cpu: "{{ (is_kvm_cpu_check.stdout | int > 0) | default(false) }}"
    docker_platform: "{{ docker_info.host_info.Architecture }}"

- name: Check Docker Ram
  ansible.builtin.assert:
    msg: "Current RAM available to docker is {{ docker_ram }} MB, minimum required is {{ prerequistes.MIN_RAM_HARD | int }} MB"
    that: "{{ (docker_ram | int) is gt(prerequistes.MIN_RAM_HARD | int) }}"
    quiet: true

- name: Check SSE4.2
  ansible.builtin.command:
    cmd: "docker run --rm busybox grep -c sse4_2 /proc/cpuinfo"
  register: docker_sse42_usage
  when: not is_kvm_cpu
  # ignore_errors: true
  failed_when: not docker_sse42_usage or docker_sse42_usage == 0
  changed_when: false
