---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
platforms:
  - name: CentOS-8
    image: quay.io/centos/centos:stream8
    pre_build_image: true
  # - name: Ubuntu-18.04
  #   image: ubuntu:18.04
  #   pre_build_image: true
  # - name: Ubuntu-20.04
  #   image: ubuntu:20.04
  #   pre_build_image: true
  # - name: Ubuntu-22.04
  #   image: ubuntu:22.04
  #   pre_build_image: true
  - name: Debian-11-bullseye-g
    image: geerlingguy/docker-debian11-ansible:latest
    pre_build_image: true
  - name: Debian-10-buster-g
    image: geerlingguy/docker-debian10-ansible:latest
    pre_build_image: true

provisioner:
  name: ansible
verifier:
  name: ansible
