---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: podman
platforms:
  - name: centos-8
    #image: quay.io/centos/centos:stream8
    image: centos:centos8
    pre_build_image: true
    # volumes:
    #   - /var/run/docker/containerd/containerd.sock:/var/run/docker.sock,rw
    # privileged: true
    # group_add: 0
  # - name: Ubuntu-18.04
  #   image: ubuntu:18.04
  #   pre_build_image: true
  # - name: Ubuntu-20.04
  #   image: ubuntu:20.04
  #   pre_build_image: true
  # - name: Ubuntu-22.04
  #   image: ubuntu:22.04
  #   pre_build_image: true
  # - name: Debian-11-bullseye-g
  #   image: geerlingguy/docker-debian11-ansible:latest
  #   pre_build_image: true
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  # - name: Debian-10-buster-g
  #   image: geerlingguy/docker-debian10-ansible:latest
  #   pre_build_image: true
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
provisioner:
  name: ansible
verifier:
  name: ansible
